services:
  flaskapp:
    build: .
    # mala mia se me olvido como hacer ta
    # image: ghcr.io/juanfeliperestrepobuitrago/project-2-tet/bookstore-monolith:v2.0.0
    container_name: bookstore-monolith-objetive2
    restart: always
    env_file:
      - .env
    ports:
      - "80:5000"
    volumes:
      - /home/ubuntu/nfs-mount:/nfs