services:
  db:
    image: mysql:8
    container_name: bookstore-db
    restart: always
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstore_user
      MYSQL_PASSWORD: bookstore_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bookstore_net

  flaskapp:
    image: ghcr.io/juanfeliperestrepobuitrago/project-2-tet/bookstore-monolith:latest
    container_name: bookstore-monolith
    restart: always
    environment:
      - FLASK_ENV=development
    ports:
      - "80:5000"
    depends_on:
      - db
    networks:
      - bookstore_net

volumes:
  db_data:
  
networks:
  bookstore_net:
    driver: bridge