services:
  auth-microservice:
    image: ghcr.io/juanfeliperestrepobuitrago/project-2-tet/auth-microservice:latest
    container_name: microservice-auth
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    ports:
      - "5001:5000"
    networks:
      - bookstore_net

  catalog-microservice:
    image: ghcr.io/juanfeliperestrepobuitrago/project-2-tet/catalog-microservice:latest
    container_name: microservice-catalog
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    ports:
      - "5002:5000"
    networks:
      - bookstore_net

  purchase-microservice:
    image: ghcr.io/juanfeliperestrepobuitrago/project-2-tet/purchase-microservice:latest
    container_name: microservice-purchase
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    ports:
      - "5003:5000"
    networks:
      - bookstore_net

  bookstore:
    image: ghcr.io/juanfeliperestrepobuitrago/project-2-tet/bookstore-monolith:latest
    container_name: bookstore
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    depends_on:
      - auth-microservice
      - catalog-microservice
      - purchase-microservice
    ports:
      - "80:5000"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/nfs-mount:/app/static
    networks:
      - bookstore_net

networks:
  bookstore_net: