services:
  auth-microservice:
    image: ghcr.io/juanfeliperestrepobuitrago/project-2-tet/auth-microservice:latest
    container_name: microservice-auth
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5001:5000"
    networks:
      - bookstore_net

  catalog-microservice:
    image: ghcr.io/juanfeliperestrepobuitrago/project-2-tet/catalog-microservice:latest
    container_name: microservice-catalog
    restart: always
    env_file:
      - .env
    ports:
      - "5002:5000"
    depends_on:
      - db
    networks:
      - bookstore_net

  purchase-microservice:
    image: ghcr.io/juanfeliperestrepobuitrago/project-2-tet/purchase-microservice:latest
    container_name: microservice-purchase
    restart: always
    env_file:
      - .env
    ports:
      - "5003:5000"
    networks:
      - bookstore_net

  bookstore:
    image: ghcr.io/juanfeliperestrepobuitrago/project-2-tet/bookstore-monolith:latest
    container_name: bookstore
    depends_on:
      - auth-microservice
      - catalog-microservice
      - purchase-microservice
    ports:
      - "80:5000"
    env_file:
      - .env
    networks:
      - bookstore_net

volumes:
  db_data:

networks:
  bookstore_net: