version: "3.8"

services:
  auth-microservice:
    image: "${AUTH_IMAGE}"
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - WRITE_ENGINE=${WRITE_ENGINE}
      - READER_ENGINE=${READER_ENGINE}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - target: 5000
        published: 5001
        protocol: tcp
        mode: host
    networks:
      - bookstore_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  catalog-microservice:
    image: "${CATALOG_IMAGE}"
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - WRITE_ENGINE=${WRITE_ENGINE}
      - READER_ENGINE=${READER_ENGINE}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - target: 5000
        published: 5002
        protocol: tcp
        mode: host
    networks:
      - bookstore_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  purchase-microservice:
    image: "${PURCHASE_IMAGE}"
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - WRITE_ENGINE=${WRITE_ENGINE}
      - READER_ENGINE=${READER_ENGINE}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - target: 5000
        published: 5003
        protocol: tcp
        mode: host
    networks:
      - bookstore_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  bookstore:
    image: "${BOOKSTORE_IMAGE}"
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - WRITE_ENGINE=${WRITE_ENGINE}
      - READER_ENGINE=${READER_ENGINE}
      - CREATION_DB=${CREATION_DB}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - CATALOG_SERVICE_URL=${CATALOG_SERVICE_URL}
      - PURCHASE_SERVICE_URL=${PURCHASE_SERVICE_URL}
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    networks:
      - bookstore_net
    depends_on:
      - auth-microservice
      - catalog-microservice
      - purchase-microservice
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  bookstore_net:
    driver: overlay
    attachable: true
