import os

SECRET_KEY = os.getenv('SECRET_KEY', 'secretkey')
SQLALCHEMY_TRACK_MODIFICATIONS = bool(os.getenv('SQLALCHEMY_TRACK_MODIFICATIONS', False))
SQLALCHEMY_DATABASE_URI_WRITE = os.getenv('WRITE_ENGINE', 'sqlite:///write.db')
SQLALCHEMY_DATABASE_URI_WRITE = os.getenv('WRITE_ENGINE')
SQLALCHEMY_DATABASE_URI_READER = os.getenv('READER_ENGINE')