services:
  flaskapp-microservice-auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservice-auth
    restart: always
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - WRITE_ENGINE=mysql+pymysql://bookstore_user:123@db/bookstore
      - READER_ENGINE=mysql+pymysql://bookstore_user:123@db/bookstore
      - SECRET_KEY=secretkey
    ports:
      - "5001:5000"
    networks:
      - bookstore_net

  db:
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstore_user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bookstore_net

volumes:
  db_data:

networks:
  bookstore_net:
