services:
  flaskapp-microservice-auth:
    image: ghcr.io/juanfeliperestrepobuitrago/project-2-tet/auth-microservice:latest
    container_name: microservice-auth
    restart: always
    env_file:
      - .env
    ports:
      - "80:5000"