services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./data/acme.sh:/etc/letsencrypt/live
    networks:
      - reverse-proxy

  acme:
    image: neilpang/acme.sh:latest
    container_name: acme-renewer
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/acme.sh:/acme.sh
      - ./reload_nginx.sh:/reload_nginx.sh
    entrypoint: ["/bin/sh","-c"]
    command: >
      # 1) Si es la primera vez, instala acme.sh y su cronjob:
      if [ ! -f /acme.sh/account.conf ]; then
        /acme.sh --install \
          --home /acme.sh \
          --accountemail "$ACME_EMAIL" \
          --dns dns_duckdns \
          --reloadcmd "/reload_nginx.sh" \
          --install-cronjob \
          --nocron
      fi &&
      /acme.sh --cron --home /acme.sh && sleep infinity
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    driver: bridge
