services:
  flaskapp-microservice-catalog:
    image: ghcr.io/juanfeliperestrepobuitrago/project-2-tet/catalog-microservice:latest
    container_name: microservice-catalog
    restart: always
    env_file:
      - .env
    ports:
      - "80:5000"