version: '3.8'

services:
  catalog:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///catalog.db
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    command: python -m flask run --host=0.0.0.0 --port=5001 