version: '3.8'

services:
  flaskapp-microservice-catalog:
    build: ./catalog-microservice
    container_name: microservice-catalog
    restart: always
    env_file:
      - .env
    ports:
      - "5002:5002"
