version: "3.8"

services:
  catalog-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: catalog_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  microservice-catalog:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      catalog-db:
        condition: service_healthy
    environment:
      DB_HOST: catalog-db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: catalog_db
      FLASK_ENV: default
      WRITE_ENGINE: mysql+pymysql://root:password@catalog-db/catalog_db
