name: Release Docker Images

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract tag name
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and Push Reverse Proxy Image to GHCR 
        uses: docker/build-push-action@v5
        with:
          context: ./reverse-proxy
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false 
          tags: |
            ghcr.io/juanfeliperestrepobuitrago/project-2-tet/reverse-proxy-acme:${{ env.TAG }}
            ghcr.io/juanfeliperestrepobuitrago/project-2-tet/reverse-proxy-acme:latest

      - name: Build and Push Bookstore-Monolith Image to GHCR 
        uses: docker/build-push-action@v5
        with:
          context: ./bookstore-monolith-2
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false 
          tags: |
            ghcr.io/juanfeliperestrepobuitrago/project-2-tet/bookstore-monolith:${{ env.TAG }}
            ghcr.io/juanfeliperestrepobuitrago/project-2-tet/bookstore-monolith:latest
      
      - name: Build and Push Auth Microservice Image to GHRC
        uses: docker/build-push-action@v5
        with:
          context: ./auth-microservice
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false 
          tags: |
            ghcr.io/juanfeliperestrepobuitrago/project-2-tet/auth-microservice:${{ env.TAG }}
            ghcr.io/juanfeliperestrepobuitrago/project-2-tet/auth-microservice:latest

      - name: Build and Push Catalog Microservice Image to GHRC
        uses: docker/build-push-action@v5
        with:
          context: ./catalog-microservice
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false 
          tags: |
            ghcr.io/juanfeliperestrepobuitrago/project-2-tet/catalog-microservice:${{ env.TAG }}
            ghcr.io/juanfeliperestrepobuitrago/project-2-tet/catalog-microservice:latest

      - name: Build and Push Purchase Microservice Image to GHRC
        uses: docker/build-push-action@v5
        with:
          context: ./purchase-microservice
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false 
          tags: |
            ghcr.io/juanfeliperestrepobuitrago/project-2-tet/purchase-microservice:${{ env.TAG }}
            ghcr.io/juanfeliperestrepobuitrago/project-2-tet/purchase-microservice:latest